# Generated by Django 3.0.2 on 2020-01-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HRRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latency', models.IntegerField()),
                ('overtime', models.IntegerField()),
                ('month', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OwnRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField(choices=[(1, 'Муу'), (2, 'Хангалтгүй'), (3, 'Дунд'), (4, 'Сайн'), (5, 'Маш сайн')], verbose_name='Ажлын хурд')),
                ('quality', models.PositiveSmallIntegerField(choices=[(1, 'Муу'), (2, 'Хангалтгүй'), (3, 'Дунд'), (4, 'Сайн'), (5, 'Маш сайн')], verbose_name='Ажлын чанар')),
                ('active', models.PositiveSmallIntegerField(choices=[(1, 'Муу'), (2, 'Хангалтгүй'), (3, 'Дунд'), (4, 'Сайн'), (5, 'Маш сайн')], verbose_name='Идэвхи санаачлага')),
                ('attitude', models.PositiveSmallIntegerField(choices=[(1, 'Муу'), (2, 'Хангалтгүй'), (3, 'Дунд'), (4, 'Сайн'), (5, 'Маш сайн')], verbose_name='Харилцаа хандлага')),
                ('month', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.PositiveSmallIntegerField(choices=[(1, 'Муу'), (2, 'Хангалтгүй'), (3, 'Дунд'), (4, 'Сайн'), (5, 'Маш сайн')], verbose_name='Ажлын хурд')),
                ('quality', models.PositiveSmallIntegerField(choices=[(1, 'Муу'), (2, 'Хангалтгүй'), (3, 'Дунд'), (4, 'Сайн'), (5, 'Маш сайн')], verbose_name='Ажлын чанар')),
                ('active', models.PositiveSmallIntegerField(choices=[(1, 'Муу'), (2, 'Хангалтгүй'), (3, 'Дунд'), (4, 'Сайн'), (5, 'Маш сайн')], verbose_name='Идэвхи санаачлага')),
                ('attitude', models.PositiveSmallIntegerField(choices=[(1, 'Муу'), (2, 'Хангалтгүй'), (3, 'Дунд'), (4, 'Сайн'), (5, 'Маш сайн')], verbose_name='Харилцаа хандлага')),
                ('month', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
