# Generated by Django 3.0.2 on 2020-01-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200115_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownrating',
            name='month',
            field=models.DateField(verbose_name='Сар'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='month',
            field=models.DateField(verbose_name='Сар'),
        ),
    ]
